export const  data = [
  {
    operation: "Subtraction",
    number1: 7527,
    number2: 165,
    maxTime: 1,
    idProgram: 1,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Multiplication",
    number1: 4994,
    number2: 6728,
    maxTime: 2,
    idProgram: 2,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Remainder",
    number1: 8809,
    number2: 7458,
    maxTime: 3,
    idProgram: 3,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Multiplication",
    number1: 6032,
    number2: 5651,
    maxTime: 4,
    idProgram: 4,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Multiplication",
    number1: 5922,
    number2: 504,
    maxTime: 3,
    idProgram: 5,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Remainder",
    number1: 5528,
    number2: 4944,
    maxTime: 3,
    idProgram: 6,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Addition",
    number1: 737,
    number2: 1603,
    maxTime: 1,
    idProgram: 7,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Addition",
    number1: 4922,
    number2: 2367,
    maxTime: 4,
    idProgram: 8,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Division",
    number1: 6268,
    number2: 7903,
    maxTime: 1,
    idProgram: 9,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Addition",
    number1: 4026,
    number2: 818,
    maxTime: 1,
    idProgram: 10,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Addition",
    number1: 5012,
    number2: 9670,
    maxTime: 2,
    idProgram: 11,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Subtraction",
    number1: 1343,
    number2: 4572,
    maxTime: 4,
    idProgram: 12,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Addition",
    number1: 8287,
    number2: 306,
    maxTime: 3,
    idProgram: 13,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Division",
    number1: 3370,
    number2: 2266,
    maxTime: 2,
    idProgram: 14,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Multiplication",
    number1: 3375,
    number2: 9404,
    maxTime: 3,
    idProgram: 15,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Division",
    number1: 4682,
    number2: 793,
    maxTime: 2,
    idProgram: 16,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Remainder",
    number1: 7332,
    number2: 3573,
    maxTime: 3,
    idProgram: 17,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Remainder",
    number1: 3227,
    number2: 2939,
    maxTime: 1,
    idProgram: 18,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Multiplication",
    number1: 4078,
    number2: 3199,
    maxTime: 4,
    idProgram: 19,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Addition",
    number1: 2605,
    number2: 8959,
    maxTime: 2,
    idProgram: 20,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Addition",
    number1: 3901,
    number2: 5287,
    maxTime: 3,
    idProgram: 21,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Remainder",
    number1: 9129,
    number2: 6204,
    maxTime: 2,
    idProgram: 22,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Subtraction",
    number1: 9894,
    number2: 1484,
    maxTime: 1,
    idProgram: 23,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Subtraction",
    number1: 6994,
    number2: 4308,
    maxTime: 4,
    idProgram: 24,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Remainder",
    number1: 4826,
    number2: 3616,
    maxTime: 1,
    idProgram: 25,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Division",
    number1: 8497,
    number2: 4879,
    maxTime: 3,
    idProgram: 26,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Remainder",
    number1: 8105,
    number2: 7672,
    maxTime: 2,
    idProgram: 27,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Multiplication",
    number1: 110,
    number2: 6948,
    maxTime: 2,
    idProgram: 28,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Multiplication",
    number1: 2014,
    number2: 6560,
    maxTime: 1,
    idProgram: 29,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Subtraction",
    number1: 9672,
    number2: 2306,
    maxTime: 4,
    idProgram: 30,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Division",
    number1: 6006,
    number2: 46,
    maxTime: 3,
    idProgram: 31,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Multiplication",
    number1: 8319,
    number2: 3320,
    maxTime: 2,
    idProgram: 32,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Addition",
    number1: 8579,
    number2: 8690,
    maxTime: 3,
    idProgram: 33,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Addition",
    number1: 2488,
    number2: 4769,
    maxTime: 2,
    idProgram: 34,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Subtraction",
    number1: 723,
    number2: 4140,
    maxTime: 4,
    idProgram: 35,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
  {
    operation: "Multiplication",
    number1: 5581,
    number2: 9063,
    maxTime: 1,
    idProgram: 36,
    error: false,
    arrivalTime: 0,
    completionTime: 0,
    returnTime: 0,
    responseTime: 0,
    waitTime: 0,
    serviceTime: 0,
  },
];
